var text = `Obedové menu podávame od 10:30 – do vypredania. Objednávky na donášku obedového menu príjmame od 9:00 – najlepšie do 11:00 hod., ale ak ste nestihli, volajte aj neskôr. Pri objednávke môžete uviesť čas, kedy chcete menu doručiť, Čas je orientačný. CENA DENNÉHO MENU V REŠTAURÁCIÍ AJ NA DONÁŠKU JE 6,30 € S POLIEVOČKOU A 5,70 € BEZ POLIEVOČKY. PONDELOK, 26.06.2023 Zeleninová s liatym cestom z celozrnnej múky /3/ 1. 120g Kurací plátok zapekaný so zeleninovým ragú (baklažán, cuketa, paradajka, bazalkové pesto) a syrom /1,7,8/ (200g ryža) 2. 120g Grilovaná bravčová panenka /1,3,7/ (½ zapekaná brokolica, ½ hranolky) 3. 120g Trojboj: vyprážané šampiňóny, ½ mini zemiakové placky, ½ kôprové halušky so syrovou omáčkou a slaninovým chipsom /1,3,7/ UTOROK, 27.06.2023 Šošovicová na kyslo /1,3,7/ 1. 120gKuracia rolka plnená šampiňónmi, kapiou a hráškom /1,7/ (200g zemiakové pyré) 2. 120g Kotlíkový guláš s domácim chlebíkom z našej piecky /1,3,7/ 3. 200g Zemiakové lokše (3ks) plnené makom, slivkovým lekvárom a orechmi, škoricovým cukrom a preliate maslom /1,3,8/ STREDA, 28.06.2023 Boršč s mäsom /12/ 1. 120g Pečené kačacie stehno na rebarborovej omáčke /7/ (200g pučené zemiaky) 2. 120g Trhaná bravčová krkovička v zemiakovej placke /1,3,7/ (100g grilovaná zelenina, 50g jogurtovo - cesnakový díp) 3. 200g Zapekané cestoviny so zeleninou, šunkou a syrom /1,3,7/ (50g zeleninový šalát) ŠTVRTOK, 29.06.2023 Tekvicová krémová s krutónmi /1,3,7/ 1. 120g Kuracia rolka plnená sušenou marhuľou, vlašskými orechmi a nivou /1,7,8/ (½ ryža, ½ hranolky) 2. 120g Pečený bravčový bôčik na pive na dusenej kyslej kapuste /7,12/ (200g nové varené zemiaky s maslom a jarnou cibuľkou) 3. 120g Cézar šalát s pizza chlebíkom (šalát, tradičná ančovičková majonéza, vajíčko, slaninka, parmezán /1,3,4,7,10/ PIATOK, 30.06.2023 Mrkvovo – kalerábový vývar /7/ 1. 120g Kurací steak s lečom z čerstvej zeleniny /1,7/ (200g zapekaný plnený zemiak s bryndzou a slaninkou) 2. 120g Dvojboj (bravčové, hovädzie) na dubákovo - smotanovej omáčke /1,7/ (½ ryža, ½ americké zemiaky) 3. 200g Zemiakové gnocchi s lososom, krevetami a paradajkami, dozdobené mozzarellou a čerstvou bazalkou /1,3,4,7/ Zoznam alergénov 1. Obilniny obsahujú lepok (pšenica, raž, jačmeň, ovos, špalda, kamut, a výrobky z nich); 2. Kôrovce a výrobky z nich; 3. Vajcia a výrobky z nich; 4. Ryby a výrobky z nich; 5. Arašidy a výrobky z nich`; 
var vyraz = /(?<=PONDELOK)[\s\S]*?(?=UTOROK)/; 
var vysledok = text.match(vyraz)[0]; 
console.log(vysledok);   
var vysledok = vstup.match(/\d+/g).filter(function (cislo) {
  return parseInt(cislo) >= 1 && parseInt(cislo) <= 14;
});

var vystup = vysledok.join(',');
console.log(vystup)